--[[
Locales['en'] = {
	-- Global
	['custom_kick'] = 'Sluta fuska och spela spelet som oss andra!',
	['blip_garage'] = 'Garage | Offentlig',
	['blip_garage_private'] = 'Garage | Privat',
	['blip_pound'] = 'Garage | Fordonsdisponering',
	['blip_police_pound'] = 'Garage | Polisens Fordonsdisponering',
	['blip_ambulance_pound'] = 'Garage | Ambulansens Fordonsdisponering',
	['garage'] = 'Garage',
	['loc_garage'] = 'Parkerad i garaget',
	['loc_pound'] = 'Vid Fordonsdisponering',
	['return'] = 'Lämna tillbaka',
	['store_vehicles'] = 'Parkera fordonet i garaget.',
	['press_to_enter'] = 'Tryck ~INPUT_PICKUP~ för att ta ut fordonet ur garaget.',
	['press_to_delete'] = 'Tryck ~INPUT_PICKUP~ för att parkera fordonet i garaget.',
	['press_to_impound'] = 'Tryck ~INPUT_PICKUP~ för tillgång till fordonsdisponering.',
	['spacer1'] = 'Om fordonet inte är här så kolla Fordonsdisponering!!!',
	['spacer2'] = '| Regnr | Fordonets namn | Plats |',
	['spacer3'] = '| Regnr | Fordonets namn |',
	['you_paid'] = 'Du betalade SEK',
	['not_enough_money'] = 'Du har inte tillräckligt med pengar!',
	['return_vehicle'] = 'Returnera fordonet.',
	['see_mechanic'] = 'Besök en mekaniker.',
	['damaged_vehicle'] = 'Fordonet är skadat!',
	['visit_mechanic'] = 'Besök en mekaniker eller laga fordonet själv.',
	['cannot_store_vehicle'] = 'Du kan inte förvara detta fordonet!',
	['no_vehicle_to_enter'] = 'Där är inget fordon att parkera i garaget.',
	['vehicle_in_garage'] = 'Ditt fordon är parkerat i garaget.',
	-- Cars
	['garage_cars'] = 'Bil Garage',
	['pound_cars'] = 'Fordonsdisponering',
	['list_owned_cars'] = 'Lista över ägda fordon.',
	['store_owned_cars'] = 'Parkera ägd bil i garaget.',
	['return_owned_cars'] = 'Returnera ägd bil.',
	['garage_nocars'] = 'Du äger inga bilar!',
	['car_is_impounded'] = 'Din bil står hos Fordonsdisponeringen.',
	-- Boats
	['garage_boats'] = 'Båt Garage',
	['pound_boats'] = 'Båt Fordonsdisponering',
	['list_owned_boats'] = 'Lista över ägda båtar.',
	['store_owned_boats'] = 'Förtöj din ägda båt.',
	['return_owned_boats'] = 'Returnera ägd båt.',
	['garage_noboats'] = 'Du äger inga båtar!',
	['boat_is_impounded'] = 'Din båt finns hos Fordonsdisponeringen.',
	-- Aircrafts
	['garage_aircrafts'] = 'Flygplans Hangar',
	['pound_aircrafts'] = 'Flygplans disponering',
	['list_owned_aircrafts'] = 'Lista över ägda Flygplan.',
	['store_owned_aircrafts'] = 'Lagra ditt ägda Flygplan.',
	['return_owned_aircrafts'] = 'Returnera ägt Flygplan.',
	['garage_noaircrafts'] = 'Du äger inga Flygplan!',
	['aircraft_is_impounded'] = 'Ditt flygplan finns hos Fordonsdisponering.',
	-- Jobs
	['pound_police'] = 'Polis Garage',
	['pound_ambulance'] = 'Ambulans Garage',
	['return_owned_policing'] = 'Returnera ägda polisfordon.',
	['return_owned_ambulance'] = 'Returnera ägda ambulansfordon.',
}
--]]